config/routes.rb
# Rails.application.routes.draw do
  # get 'users/new'
#   # get 'static_pages/home'
#   # get '/home', to: 'static_pages/home't

#   # get 'static_pages/help'
#   get '/help', to: 'static_pages/help'

#   # get 'static_pages/about'
#   get '/about', to: 'static_pages/about'

#   # get 'static_pages/contact'
#   get '/contact', to: 'static_pages/contact'
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#   root 'static_pages#home'

# end

Rails.application.routes.draw do
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                                             format: { with: VALID_EMAIL_REGEX },
                                             uniqueness: true
                                            # uniqueness: case_sensitive: false
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # def hello
    #     render html:"hi"
    # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    #Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title     
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
The <a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="https://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script
src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.j
s">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html>
<html>
  <head>
    <%# <title><%= yield(:title)  | Ruby on Rails Tutorial Sample App</title> %>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
-->

<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-
    track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-
    track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<!--<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
<body>
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.</p>
</body>
</html>
-->
<div class="center jumbotron">
<h1>Welcome to the Sample App</h1>
<h2>
This is the about page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.
</h2>
<%= link_to "Sign up now!", '#', class: "btn btn-lg btn-
primary" %>
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width:
"200"),
"https://rubyonrails.org/" %>

app/views/static_pages/contact.html.erb
<div class="center jumbotron">
<h1>Welcome to the Sample App</h1>
<h2>
This is the contact page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.
</h2>
<%= link_to "Sign up now!", '#', class: "btn btn-lg btn-
primary" %>
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width:
"200"),
"https://rubyonrails.org/" %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<body>
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.</p>
</body>
</html>

app/views/static_pages/home.html.erb
<!--<% provide(:title, "Home") %>
<!DOCTYPE html>
<%# <html> %>
<%# <head> %>
<%# <title><%= yield(:title) | Ruby on Rails Tutorial Sample App</title> %> 
<%# </head> %>
<html>
<body>
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.</p>
</body>
</html>
-->


<div class="center jumbotron">
<h1>Welcome to the Sample App</h1>
<h2>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-
primary" %>
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width:
"200"),
"https://rubyonrails.org/" %>

app/views/users/new.html.erb
<%# <h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p> %>


<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>